config {
  type: "table",
  database: "pipeline-muni",
  schema: "thelook_ecommerce",
  name: "distribution_centers",
  description: "Staging table for events with formatting cleaned",
  columns: {
    id: "Unique distribution center identifier",
    name: "Name of the distribution center", 
    latitude: "Latitude of the distribution center",
    longitude: "Longitude of the distribution center",
    distribution_center_geom: "Geom of the distribution center",
  },
  assertions: {
    uniqueKey: ["id"],
    nonNull: ["id", "name", "latitude", "longitude", "distribution_center_geom"]
  }
}

SELECT 
    id,
    name, 
    latitude,
    longitude,
    ST_GEOGFROMTEXT(distribution_center_geom) AS distribution_center_geom
FROM ${ref("raw_distribution_centers")}
