-- definitions/staging/stg_thelook_ecommerce__order_items.sqlx
-- Cleans and standardizes the raw order_items data.

config {
  type: "view",
  schema: "thelook_ecommerce_staging",
  assertions: {
    uniqueKey: ["order_item_id"],
    nonNull: ["order_item_id", "order_id", "user_id", "product_id"]
  }
}

SELECT
  id,
  order_id,
  user_id,
  product_id,
  inventory_item_id,
  INITCAP(status) AS status,
  created_at,
  shipped_at,
  delivered_at,
  returned_at
FROM
  ${ref("order_items_raw")}
