
config {
  type: "view",
  schema: "thelook_ecommerce_staging",

}

SELECT
  id,
  cost,
  -- Use COALESCE to replace NULLs with a standard value.
  COALESCE(INITCAP(category), 'Unknown') AS category,
  name,
  COALESCE(brand, 'Unknown') AS brand,
  retail_price,
  department,
  sku
FROM
  ${ref("products_raw")}
-- Filter out records with invalid business logic at the earliest stage.
WHERE retail_price > 0